appName: clientservice
dockerImageName: mahdiboudaouara/reactappimage
imageTag: 0.1.58-62
replicaCount: 1
containerPort: 80
containerEnvVars:
  - name: REACT_APP_USER_SERVER
    value: "194-195-247-90.ip.linodeusercontent.com"
  - name: REACT_APP_AUCTION_SERVER
    value: "194-195-247-90.ip.linodeusercontent.com"
  - name: REACT_APP_BID_SERVER
    value: "194-195-247-90.ip.linodeusercontent.com"
  - name: REACT_APP_CLIENT
    value: "194-195-247-90.ip.linodeusercontent.com"
  - name: REACT_APP_CLIENT_PORT
    value: "80"

servicePort: 80
serviceType: ClusterIP
