name: ingress
annotations:
- name: kubernetes.io/ingress.class
  value: nginx
- name: nginx.ingress.kubernetes.io/rewrite-target
  value: "/"
hostname: 194-195-247-34.ip.linodeusercontent.com
paths: 
- path: "/backend/auction"
  type: Prefix
  serviceName: auctionservice
  servicePort: "3003"

- path: "/images"
  type: Prefix
  serviceName: auctionservice
  servicePort: "80"

- path: "/backend/user"
  type: Prefix
  serviceName: userservice
  servicePort: "3004"

- path: "/backend/bid"
  type: Prefix
  serviceName: bidservice
  servicePort: "3002"

- path: "/"
  type: Prefix
  serviceName: client
  servicePort: "80"