ingress:
  enabled: true
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  hosts:
    - host: 194-195-247-34.ip.linodeusercontent.com
      http:
        paths:
          - path: /backend/auction
            backend:
              serviceName: auctionservice
              servicePort: 3003
          - path: /images
            backend:
              serviceName: auctionservice
              servicePort: 80
          - path: /backend/user
            backend:
              serviceName: userservice
              servicePort: 3004
          - path: /backend/bid
            backend:
              serviceName: bidservice
              servicePort: 3002
          - path: /
            backend:
              serviceName: clientservice
              servicePort: 80
