ingressName: ingress
ingressName: 143-42-223-116.ip.linodeusercontent.com
pathLinks: 
- pathLink: /backend/auction
  type: Prefix
  serviceName: auctionservice
  servicePort: 3003

- pathLink: /images
  type: Prefix
  serviceName: auctionservice
  servicePort: 80

- pathLink: /backend/user
  type: Prefix
  serviceName: userservice
  servicePort: 3004

- pathLink: /backend/bid
  type: Prefix
  serviceName: bidservice
  servicePort: 3002

- pathLink: /
  type: Prefix
  serviceName: clientservice
  servicePort: 80